# Generated by Django 5.1.6 on 2025-02-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=202)),
                ('full_name', models.CharField(max_length=202)),
                ('body_user', models.CharField(max_length=202)),
                ('image', models.FileField(upload_to='about/')),
                ('twitter', models.CharField(max_length=202)),
                ('facebook', models.CharField(max_length=202)),
                ('instagram', models.CharField(max_length=202)),
                ('description', models.TextField()),
                ('how_i_work', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
